services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    tty: true
    stdin_open: true
    command: ["python", "-u", "app.py"]





