
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    stdin_open: true
    tty: true

